import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import test from 'node:test'

const tauriLib = readFileSync(new URL('../../../../../../crates/atlas-tauri/src/lib.rs', import.meta.url), 'utf8')
const bridge = readFileSync(new URL('../../../lib/bridge.ts', import.meta.url), 'utf8')
const surface = readFileSync(new URL('../AtlasAiSurface.tsx', import.meta.url), 'utf8')
const intelligence = readFileSync(new URL('../awisIntelligence.ts', import.meta.url), 'utf8')
const memory = readFileSync(new URL('../awisWorkspaceMemory.ts', import.meta.url), 'utf8')

test('AWIS workspace brain has a bounded native folder scan command', () => {
  assert.match(tauriLib, /async fn atlas_scan_workspace_brain/)
  assert.match(tauriLib, /MAX_FILES: usize = 6_000/)
  assert.match(tauriLib, /MAX_DEPTH: usize = 6/)
  assert.match(tauriLib, /should_ignore_dir/)
  assert.match(tauriLib, /node_modules/)
  assert.match(tauriLib, /target/)
  assert.match(tauriLib, /generate_handler!\[[\s\S]*atlas_scan_workspace_brain/)
})

test('AWIS workspace brain is exposed through the Desktop bridge and Surface', () => {
  assert.match(bridge, /scanWorkspaceBrain\(workspacePath: string\)/)
  assert.match(bridge, /atlas_scan_workspace_brain/)
  assert.match(surface, /bridge\.scanWorkspaceBrain\(workspacePath\)/)
  assert.match(surface, /WORKSPACE_BRAIN_CACHE_TTL_MS/)
  assert.match(surface, /WORKSPACE_BRAIN_SESSION_CACHE_TTL_MS/)
  assert.match(surface, /loadWorkspaceBrainCache\(workspacePath\)/)
  assert.match(surface, /saveWorkspaceBrainCache\(workspacePath, snapshot\)/)
  assert.match(surface, /readWorkspaceBrainCacheStore\(localStorage\)/)
  assert.match(surface, /saveWorkspaceBrainCacheStore\(localStorage, workspacePath, snapshot\)/)
  assert.match(surface, /shouldRefresh: Date\.now\(\) - durableEntry\.cachedAt > WORKSPACE_BRAIN_SESSION_CACHE_TTL_MS/)
  assert.match(surface, /setWorkspaceBrain\(cached\.snapshot\)[\s\S]*setWorkspaceBrainLoading\(cached\.shouldRefresh\)/)
  assert.match(surface, /\.catch\(\(\) => \{[\s\S]*if \(!cached\) setWorkspaceBrain\(null\)[\s\S]*setWorkspaceBrainLoading\(false\)/)
  assert.match(surface, /learnAwisWorkspaceMemory/)
  assert.match(surface, /recordAwisWorkspaceInteraction/)
  assert.match(surface, /recordAwisWorkspaceMaintenance/)
  assert.match(surface, /saveAwisWorkspaceMemory/)
  assert.match(surface, /buildAwisWorkspaceContextPack/)
  assert.match(surface, /buildAwisWorkspaceProviderCapsule/)
  assert.match(surface, /buildAwisWorkspaceSpaceProjection\(projectSpaceContextPacks\)/)
  assert.match(surface, /buildAwisWorkspaceArtifact\(awisWorkspaceContextPack\)/)
  assert.match(surface, /buildAwisWorkspaceTaskContextProjection/)
  assert.match(surface, /saveAwisWorkspaceArtifact\(artifact\)/)
  assert.match(surface, /awisAutoSavedArtifactHashesRef/)
  assert.match(surface, /awisAutoSavedArtifactHashesRef\.current\.has\(artifact\.artifact_hash\)/)
  assert.match(surface, /awisAutoSavedArtifactHashesRef\.current\.add\(artifact\.artifact_hash\)/)
  assert.match(surface, /const handleAwisRefreshFolderMap = useCallback/)
  assert.match(surface, /const rememberAwisMaintenance = useCallback/)
  assert.match(surface, /bridge\.scanWorkspaceBrain\(workspacePath\)/)
  assert.match(surface, /const handleAwisPreserveArtifact = useCallback/)
  assert.match(surface, /action: 'preserve_artifact'/)
  assert.match(surface, /action: 'open_side_by_side'/)
  assert.match(surface, /Ouro AWIS preservado para a próxima conversa/)
  assert.match(surface, /onProjectSpaceContextPacksChange=\{setProjectSpaceContextPacks\}/)
  assert.match(surface, /const buildAwisSendContext = useCallback/)
  assert.match(surface, /providerCapsule \? \[providerCapsule\] : \[\]/)
  assert.match(surface, /conversationContext: sendContext\.conversationContext/)
  assert.match(surface, /registerAwisTraceContext\(trace, 'conversation', sendContext\.taskContext\)/)
  assert.match(surface, /atlas\.lastTerminalTrace/)
  assert.match(surface, /rememberAwisInteraction\(context\?\.channel \?\? 'conversation', trace, context\?\.taskContext \?\? null\)/)
  assert.match(surface, /workspaceBrainLoading/)
  assert.match(surface, /workspaceBrain: workspaceBrainLoading \? null : workspaceBrain/)
})

test('AWIS command center surfaces living brain signals without raw projection names', () => {
  assert.match(surface, /workspaceContinuity=\{awisWorkspaceContextPack\?\.continuity \?\? null\}/)
  assert.match(surface, /workspaceAutomation=\{awisWorkspaceContextPack\?\.automation \?\? null\}/)
  assert.match(surface, /workspaceConfidence=\{awisWorkspaceContextPack\?\.confidence \?\? null\}/)
  assert.match(surface, /workspaceLivingGraph=\{awisWorkspaceContextPack\?\.living_graph \?\? null\}/)
  assert.match(surface, /workspaceRelations=\{workspaceRelations\}/)
  assert.match(surface, /workspacePreflight=\{awisWorkspaceContextPack\?\.preflight \?\? null\}/)
  assert.match(surface, /workspaceTwin=\{awisWorkspaceContextPack\?\.workspace_twin \?\? null\}/)
  assert.match(surface, /workspaceLaunchContract=\{awisWorkspaceContextPack\?\.launch_contract \?\? null\}/)
  assert.match(surface, /const effectiveWorkspaceNextSessionBrain =[\s\S]*workspaceNextSessionBrain \?\? awisWorkspaceContextPack\?\.next_session_brain \?\? null/)
  assert.match(surface, /workspaceNextSessionBrain=\{effectiveWorkspaceNextSessionBrain\}/)
  assert.match(surface, /workspaceHandoffPack=\{workspaceHandoffPack\}/)
  assert.match(surface, /onRefreshFolderMap=\{handleAwisRefreshFolderMap\}/)
  assert.match(surface, /onPreserveArtifact=\{handleAwisPreserveArtifact\}/)
  assert.match(surface, /workspaceConfidence: AwisWorkspaceConfidenceProjection \| null/)
  assert.match(surface, /workspaceLivingGraph: AwisWorkspaceLivingGraphProjection \| null/)
  assert.match(surface, /workspaceRelations: AwisWorkspaceRelationProjection \| null/)
  assert.match(surface, /workspacePreflight: AwisWorkspacePreflightProjection \| null/)
  assert.match(surface, /workspaceTwin: AwisWorkspaceTwinProjection \| null/)
  assert.match(surface, /workspaceLaunchContract: AwisWorkspaceLaunchContractProjection \| null/)
  assert.match(surface, /workspaceNextSessionBrain: AwisWorkspaceNextSessionBrainProjection \| null/)
  assert.match(surface, /workspaceHandoffPack: AwisWorkspaceHandoffProjection \| null/)
  assert.match(surface, /const confidenceLeader = workspaceConfidence/)
  assert.match(surface, /const continuityLeader = workspaceContinuity\?\.restore_priority\[0\] \?\? null/)
  assert.match(surface, /const maintenanceLeader = workspaceAutomation\?\.maintenance_queue\[0\] \?\? null/)
  assert.match(surface, /const connectionLeader = workspaceRelations\?\.connection_contracts\[0\] \?\? null/)
  assert.match(surface, /const awisLivingQueue = \[/)
  assert.match(surface, /actionLabel: maintenanceLeader\.action === 'refresh_folder_map'/)
  assert.match(surface, /onAction: maintenanceLeader\.action === 'refresh_folder_map'/)
  assert.match(surface, /const graphLeader = workspaceLivingGraph/)
  assert.match(surface, /const preflightBlockingGate = workspacePreflight/)
  assert.match(surface, /const twinPrimaryComponent = workspaceTwin/)
  assert.match(surface, /const launchPrimaryLoad = workspaceLaunchContract/)
  assert.match(surface, /launchMaintenance/)
  assert.match(surface, /confidence-fallback/)
  assert.match(surface, /continuity-fallback/)
  assert.match(surface, /maintenance-fallback/)
  assert.match(surface, /aria-label="Sinais vivos do AWIS"/)
  assert.match(surface, /aria-label="Fila viva AWIS"/)
  assert.match(surface, /item\.actionLabel && item\.onAction/)
  assert.match(surface, /Confiança/)
  assert.match(surface, /Continuidade/)
  assert.match(surface, /Manter vivo/)
  assert.match(surface, /Repos conectados/)
  assert.match(surface, /salvar ouro/)
  assert.match(surface, /reusar só com validação local/)
  assert.match(surface, /Pré-checagem/)
  assert.match(surface, /Mapa vivo/)
  assert.match(surface, /Partida viva/)
  assert.match(surface, /Handoff/)
  assert.match(surface, /Partida/)
  assert.match(surface, /pré-checagem pronta/)
  assert.match(surface, /mapa vivo do projeto/)
  assert.match(surface, /partida viva/)
  assert.match(surface, /partida com memória/)
  assert.match(surface, /handoff seguro/)
  assert.doesNotMatch(surface, /workspace_confidence_projection|workspace_continuity_projection|workspace_automation_projection|workspace_preflight_projection|workspace_twin_projection|workspace_launch_contract_projection|genome_hash/)
})

test('AWIS intelligence treats the folder map as a real command-center gate', () => {
  assert.match(intelligence, /workspaceBrainRequested/)
  assert.match(intelligence, /mapear pasta local/)
  assert.match(intelligence, /recuperar mapa local/)
  assert.match(intelligence, /mapa local/)
  assert.match(intelligence, /comandos inferidos/)
})

test('AWIS workspace memory persists incremental learning without raw source text', () => {
  assert.match(memory, /atlas\.awis\.workspace_memory\.v1/)
  assert.match(memory, /stableSignals/)
  assert.match(memory, /operationalSignals/)
  assert.match(memory, /contextPackAppliedCount/)
  assert.match(memory, /atlas\.awis\.workspace_learning_projection\.v1/)
  assert.match(memory, /buildAwisWorkspaceLearningProjection/)
  assert.match(memory, /atlas\.awis\.workspace_space_projection\.v1/)
  assert.match(memory, /atlas\.awis\.workspace_artifact\.v1/)
  assert.match(memory, /atlas\.awis\.workspace_artifact_lake_summary\.v1/)
  assert.match(memory, /atlas\.awis\.workspace_topology_projection\.v1/)
  assert.match(memory, /buildAwisWorkspaceTopologyProjection/)
  assert.match(memory, /topology_ready/)
  assert.match(memory, /atlas\.awis\.workspace_component_memory_projection\.v1/)
  assert.match(memory, /buildAwisWorkspaceComponentMemoryProjection/)
  assert.match(memory, /component_memory: AwisWorkspaceComponentMemoryProjection \| null/)
  assert.match(memory, /atlas\.awis\.workspace_semantic_index_projection\.v1/)
  assert.match(memory, /buildAwisWorkspaceSemanticIndexProjection/)
  assert.match(memory, /semantic_index: AwisWorkspaceSemanticIndexProjection \| null/)
  assert.match(memory, /semantic_index_projection/)
  assert.match(memory, /semantic_matches/)
  assert.match(memory, /atlas\.awis\.workspace_impact_map_projection\.v1/)
  assert.match(memory, /buildAwisWorkspaceImpactMapProjection/)
  assert.match(memory, /impact_map: AwisWorkspaceImpactMapProjection \| null/)
  assert.match(memory, /impact_map_projection/)
  assert.match(memory, /impact_radius/)
  assert.match(memory, /atlas\.awis\.workspace_preflight_projection\.v1/)
  assert.match(memory, /buildAwisWorkspacePreflightProjection/)
  assert.match(memory, /preflight: AwisWorkspacePreflightProjection \| null/)
  assert.match(memory, /preflight_projection/)
  assert.match(memory, /execution_lanes/)
  assert.match(memory, /atlas\.awis\.workspace_twin_projection\.v1/)
  assert.match(memory, /buildAwisWorkspaceTwinProjection/)
  assert.match(memory, /workspace_twin: AwisWorkspaceTwinProjection \| null/)
  assert.match(memory, /workspace_twin_projection/)
  assert.match(memory, /genome_hash/)
  assert.match(memory, /context_autopilot/)
  assert.match(memory, /atlas\.awis\.workspace_relation_projection\.v1/)
  assert.match(memory, /buildAwisWorkspaceRelationProjection/)
  assert.match(memory, /relations_ready/)
  assert.match(memory, /transfer_matrix/)
  assert.match(memory, /shared_context_gold/)
  assert.match(memory, /shared_validation_plans/)
  assert.match(memory, /shared_recovery_patterns/)
  assert.match(memory, /contextGoldLabelsForRelation/)
  assert.match(memory, /validationPlanLabelsForRelation/)
  assert.match(memory, /recoveryPatternLabelsForRelation/)
  assert.match(memory, /atlas\.awis\.workspace_startup_briefing\.v1/)
  assert.match(memory, /startup_briefing: AwisWorkspaceStartupBriefing \| null/)
  assert.match(memory, /atlas\.awis\.workspace_startup_playbook\.v1/)
  assert.match(memory, /startup_playbook: AwisWorkspaceStartupPlaybook \| null/)
  assert.match(memory, /atlas\.awis\.workspace_task_context_projection\.v1/)
  assert.match(memory, /buildAwisWorkspaceTaskContextProjection/)
  assert.match(memory, /working_set:/)
  assert.match(memory, /folder_focus:/)
  assert.match(memory, /buildFolderFocusPlan/)
  assert.match(memory, /primary_component: string \| null/)
  assert.match(memory, /task_gold:/)
  assert.match(memory, /buildTaskGoldSelection/)
  assert.match(memory, /evidence_gate:/)
  assert.match(memory, /buildTaskEvidenceGate/)
  assert.match(memory, /context_budget:/)
  assert.match(memory, /buildTaskContextBudget/)
  assert.match(memory, /component_intent_ranking/)
  assert.match(memory, /buildComponentIntentRanking/)
  assert.match(memory, /component_context_packs/)
  assert.match(memory, /buildComponentContextPacks/)
  assert.match(memory, /atlas\.awis\.workspace_provider_capsule\.v1/)
  assert.match(memory, /buildAwisWorkspaceProviderCapsule/)
  assert.match(memory, /atlas\.awis\.workspace_execution_doctrine_projection\.v1/)
  assert.match(memory, /buildAwisWorkspaceExecutionDoctrineProjection/)
  assert.match(memory, /execution_doctrine: AwisWorkspaceExecutionDoctrineProjection \| null/)
  assert.match(memory, /doctrine_drivers/)
  assert.match(memory, /preflight_gates/)
  assert.match(memory, /attach_component_keys: true/)
  assert.match(memory, /atlas\.awis\.workspace_provider_strategy_projection\.v1/)
  assert.match(memory, /buildAwisWorkspaceProviderStrategyProjection/)
  assert.match(memory, /provider_strategy: AwisWorkspaceProviderStrategyProjection \| null/)
  assert.match(memory, /record_latency: true/)
  assert.match(memory, /atlas\.awis\.workspace_task_router_projection\.v1/)
  assert.match(memory, /buildAwisWorkspaceTaskRouterProjection/)
  assert.match(memory, /task_router: AwisWorkspaceTaskRouterProjection \| null/)
  assert.match(memory, /record_selected_route: true/)
  assert.match(memory, /intent_signals/)
  assert.match(memory, /evidence_plan/)
  assert.match(memory, /automation_hooks/)
  assert.match(memory, /intentSignalsForTaskRoute/)
  assert.match(memory, /buildTaskRouteEvidencePlan/)
  assert.match(memory, /buildTaskRouteAutomationHooks/)
  assert.match(memory, /routeKey: string \| null/)
  assert.match(memory, /routeLabel: string \| null/)
  assert.match(memory, /contextGoldLabels: string\[\]/)
  assert.match(memory, /buildContextGoldOperationalMemory/)
  assert.match(surface, /contextGoldLabels: taskContext\?\.recommended_context\.task_gold\.map/)
  assert.match(surface, /routeKey: taskContext\?\.task_kind \? `task:\$\{taskContext\.task_kind\}` : null/)
  assert.match(memory, /atlas\.awis\.workspace_continuity_projection\.v1/)
  assert.match(memory, /buildAwisWorkspaceContinuityProjection/)
  assert.match(memory, /continuity: AwisWorkspaceContinuityProjection \| null/)
  assert.match(memory, /atlas\.awis\.workspace_automation_projection\.v1/)
  assert.match(memory, /buildAwisWorkspaceAutomationProjection/)
  assert.match(memory, /external_side_effects_allowed: false/)
  assert.match(memory, /atlas\.awis\.workspace_confidence_projection\.v1/)
  assert.match(memory, /buildAwisWorkspaceConfidenceProjection/)
  assert.match(memory, /confidence: AwisWorkspaceConfidenceProjection \| null/)
  assert.match(memory, /atlas\.awis\.workspace_living_graph_projection\.v1/)
  assert.match(memory, /buildAwisWorkspaceLivingGraphProjection/)
  assert.match(memory, /living_graph: AwisWorkspaceLivingGraphProjection \| null/)
  assert.match(memory, /atlas\.awis\.workspace_context_kernel_projection\.v1/)
  assert.match(memory, /buildAwisWorkspaceContextKernelProjection/)
  assert.match(memory, /context_kernel: AwisWorkspaceContextKernelProjection \| null/)
  assert.match(memory, /atlas\.awis\.workspace_self_improvement_projection\.v1/)
  assert.match(memory, /buildAwisWorkspaceSelfImprovementProjection/)
  assert.match(memory, /self_improvement: AwisWorkspaceSelfImprovementProjection \| null/)
  assert.match(memory, /atlas\.awis\.workspace_memory_freshness_projection\.v1/)
  assert.match(memory, /buildAwisWorkspaceMemoryFreshnessProjection/)
  assert.match(memory, /memory_freshness: AwisWorkspaceMemoryFreshnessProjection \| null/)
  assert.match(memory, /atlas\.awis\.workspace_retention_projection\.v1/)
  assert.match(memory, /buildAwisWorkspaceRetentionProjection/)
  assert.match(memory, /retention: AwisWorkspaceRetentionProjection \| null/)
  assert.match(memory, /atlas\.awis\.workspace_memory_consolidation_projection\.v1/)
  assert.match(memory, /buildAwisWorkspaceMemoryConsolidationProjection/)
  assert.match(memory, /memory_consolidation: AwisWorkspaceMemoryConsolidationProjection \| null/)
  assert.match(memory, /memory_consolidation_projection/)
  assert.match(memory, /normalizeMemoryConsolidationProjection/)
  assert.match(memory, /atlas\.awis\.workspace_startup_orchestration_projection\.v1/)
  assert.match(memory, /buildAwisWorkspaceStartupOrchestrationProjection/)
  assert.match(memory, /startup_orchestration: AwisWorkspaceStartupOrchestrationProjection \| null/)
  assert.match(memory, /atlas\.awis\.workspace_launch_contract_projection\.v1/)
  assert.match(memory, /buildAwisWorkspaceLaunchContractProjection/)
  assert.match(memory, /launch_contract: AwisWorkspaceLaunchContractProjection \| null/)
  assert.match(memory, /launch_contract_projection/)
  assert.match(memory, /atlas\.awis\.workspace_session_gold_projection\.v1/)
  assert.match(memory, /buildAwisWorkspaceSessionGoldProjection/)
  assert.match(memory, /session_gold: AwisWorkspaceSessionGoldProjection \| null/)
  assert.match(memory, /raw_user_message_included: false/)
  assert.match(memory, /taskKind\?: AwisWorkspaceTaskContextProjection\['task_kind'\]/)
  assert.match(memory, /task_memory:/)
  assert.match(memory, /trusted_task_commands/)
  assert.match(memory, /validation_plans/)
  assert.match(memory, /buildTaskValidationPlans/)
  assert.match(memory, /next_session_contract/)
  assert.match(memory, /buildTaskNextSessionContract/)
  assert.match(memory, /recovery_playbook/)
  assert.match(memory, /buildTaskRecoveryPlaybook/)
  assert.match(memory, /tarefa:\$\{input\.taskKind\}/)
  assert.match(memory, /never_start_cold: true/)
  assert.match(memory, /internal_ids_included: false/)
  assert.match(memory, /driftEvents/)
  assert.match(memory, /workspaceBrainFingerprint/)
  assert.doesNotMatch(memory, /readFileSync|read_to_string/)
})
