import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import test from 'node:test'

const tauriLib = readFileSync(new URL('../../../../../../crates/atlas-tauri/src/lib.rs', import.meta.url), 'utf8')
const bridge = readFileSync(new URL('../../../lib/bridge.ts', import.meta.url), 'utf8')
const surface = readFileSync(new URL('../AtlasAiSurface.tsx', import.meta.url), 'utf8')
const threadList = readFileSync(new URL('../components/AtlasAiThreadList.tsx', import.meta.url), 'utf8')
const intelligence = readFileSync(new URL('../awisIntelligence.ts', import.meta.url), 'utf8')
const memory = readFileSync(new URL('../awisWorkspaceMemory.ts', import.meta.url), 'utf8')
const useAtlasAi = readFileSync(new URL('../useAtlasAi.ts', import.meta.url), 'utf8')
const contract = readFileSync(new URL('../contract.ts', import.meta.url), 'utf8')

test('AWIS workspace brain has a bounded native folder scan command', () => {
  assert.match(tauriLib, /async fn atlas_scan_workspace_brain/)
  assert.match(tauriLib, /MAX_FILES: usize = 6_000/)
  assert.match(tauriLib, /MAX_DEPTH: usize = 6/)
  assert.match(tauriLib, /MAX_DOC_DIGESTS: usize = 16/)
  assert.match(tauriLib, /struct WorkspaceBrainDocDigest/)
  assert.match(tauriLib, /struct WorkspaceBrainDependencyEdge/)
  assert.match(tauriLib, /digest_workspace_document/)
  assert.match(tauriLib, /session:bootstrap antes de implementar|sessão:bootstrap antes de implementar/)
  assert.match(tauriLib, /should_ignore_dir/)
  assert.match(tauriLib, /detect_dir_signals/)
  assert.match(tauriLib, /is_important_dir/)
  assert.match(tauriLib, /Atlas AI surface/)
  assert.match(tauriLib, /Sensitive execution zone/)
  assert.match(tauriLib, /Mobile app/)
  assert.match(tauriLib, /last_segment\.starts_with\("atlas-"\)/)
  assert.match(tauriLib, /node_modules/)
  assert.match(tauriLib, /target/)
  assert.match(tauriLib, /is_relevant_package_script/)
  assert.match(tauriLib, /atlas-ai:test/)
  assert.match(tauriLib, /collect_manifest_intelligence/)
  assert.match(tauriLib, /detect_package_json_signals/)
  assert.match(tauriLib, /detect_composer_signals/)
  assert.match(tauriLib, /collect_package_dependency_edges/)
  assert.match(tauriLib, /collect_package_workspace_edges/)
  assert.match(tauriLib, /collect_pnpm_workspace_intelligence/)
  assert.match(tauriLib, /pnpm_workspace_members/)
  assert.match(tauriLib, /read_small_text\(path, 64 \* 1024\)/)
  assert.match(tauriLib, /package_workspace_members/)
  assert.match(tauriLib, /Monorepo workspace/)
  assert.match(tauriLib, /pnpm workspace/)
  assert.match(tauriLib, /kind: "workspace"\.into\(\)/)
  assert.match(tauriLib, /workspace_member_value/)
  assert.match(tauriLib, /workspace_member_text_value/)
  assert.match(tauriLib, /collect_composer_dependency_edges/)
  assert.match(tauriLib, /is_relevant_dependency_name/)
  assert.match(tauriLib, /dedupe_dependency_edges\(&mut dependency_edges\)/)
  assert.match(tauriLib, /Browser automation tests/)
  assert.match(tauriLib, /Auth\/Security/)
  assert.match(tauriLib, /package_manager_for_manifest/)
  assert.match(tauriLib, /pnpm-workspace\.yaml/)
  assert.match(tauriLib, /manifest_command\(relative, &format!\("\{package_manager\} run \{key\}"\)\)/)
  assert.match(tauriLib, /cd \{dir\} && \{command\}/)
  assert.match(tauriLib, /sort_workspace_commands\(&mut commands\)/)
  assert.match(tauriLib, /async fn atlas_awis_memory_load_all/)
  assert.match(tauriLib, /async fn atlas_awis_memory_save/)
  assert.match(tauriLib, /async fn atlas_awis_artifacts_load_all/)
  assert.match(tauriLib, /async fn atlas_awis_artifacts_save/)
  assert.match(tauriLib, /async fn atlas_awis_project_spaces_load_all/)
  assert.match(tauriLib, /async fn atlas_awis_project_spaces_save/)
  assert.match(tauriLib, /desktop-awis/)
  assert.match(tauriLib, /workspace-memory\.json/)
  assert.match(tauriLib, /workspace-artifacts\.json/)
  assert.match(tauriLib, /project-spaces\.json/)
  assert.match(tauriLib, /atlas_awis_memory_load_all/)
  assert.match(tauriLib, /atlas_awis_memory_save/)
  assert.match(tauriLib, /atlas_awis_artifacts_load_all/)
  assert.match(tauriLib, /atlas_awis_artifacts_save/)
  assert.match(tauriLib, /atlas_awis_project_spaces_load_all/)
  assert.match(tauriLib, /atlas_awis_project_spaces_save/)
  assert.match(tauriLib, /generate_handler!\[[\s\S]*atlas_scan_workspace_brain/)
})

test('AWIS workspace brain is exposed through the Desktop bridge and Surface', () => {
  assert.match(bridge, /scanWorkspaceBrain\(workspacePath: string\)/)
  assert.match(bridge, /atlas_scan_workspace_brain/)
  assert.match(bridge, /AtlasWorkspaceBrainDocDigest/)
  assert.match(bridge, /AtlasWorkspaceBrainDependencyEdge/)
  assert.match(bridge, /docDigests: arrayValue\(r\.docDigests \?\? r\.doc_digests\)/)
  assert.match(bridge, /dependencyEdges: arrayValue\(r\.dependencyEdges \?\? r\.dependency_edges\)/)
  assert.match(bridge, /loadAwisWorkspaceMemoryStore\(\)/)
  assert.match(bridge, /saveAwisWorkspaceMemory\(workspaceKey: string, memory: unknown\)/)
  assert.match(bridge, /loadAwisWorkspaceArtifactStore\(\)/)
  assert.match(bridge, /saveAwisWorkspaceArtifacts\(workspaceKey: string, artifacts: unknown\[\]\)/)
  assert.match(bridge, /loadAwisProjectSpacesStore\(\)/)
  assert.match(bridge, /saveAwisProjectSpacesStore\(spaces: unknown\[\], receipts: unknown\[\]\)/)
  assert.match(bridge, /atlas_awis_memory_load_all/)
  assert.match(bridge, /atlas_awis_memory_save/)
  assert.match(bridge, /atlas_awis_artifacts_load_all/)
  assert.match(bridge, /atlas_awis_artifacts_save/)
  assert.match(bridge, /atlas_awis_project_spaces_load_all/)
  assert.match(bridge, /atlas_awis_project_spaces_save/)
  assert.match(surface, /bridge\.scanWorkspaceBrain\(workspacePath\)/)
  assert.match(surface, /bridge\.loadAwisWorkspaceMemoryStore\(\)/)
  assert.match(surface, /bridge\.saveAwisWorkspaceMemory\(memory\.workspaceKey, memory\)/)
  assert.match(surface, /bridge\.loadAwisWorkspaceArtifactStore\(\)/)
  assert.match(surface, /bridge\.saveAwisWorkspaceArtifacts\(/)
  assert.match(surface, /mergeAwisWorkspaceMemoryStores/)
  assert.match(surface, /mergeAwisWorkspaceArtifactStores/)
  assert.match(surface, /saveAwisWorkspaceMemories\(merged\)/)
  assert.match(surface, /saveAwisWorkspaceArtifactStore\(merged\)/)
  assert.match(surface, /WORKSPACE_BRAIN_CACHE_TTL_MS/)
  assert.match(surface, /WORKSPACE_BRAIN_SESSION_CACHE_TTL_MS/)
  assert.match(surface, /loadWorkspaceBrainCache\(workspacePath\)/)
  assert.match(surface, /saveWorkspaceBrainCache\(workspacePath, snapshot\)/)
  assert.match(surface, /readWorkspaceBrainCacheStore\(localStorage\)/)
  assert.match(surface, /saveWorkspaceBrainCacheStore\(localStorage, workspacePath, snapshot\)/)
  assert.match(surface, /shouldRefresh: Date\.now\(\) - durableEntry\.cachedAt > WORKSPACE_BRAIN_SESSION_CACHE_TTL_MS/)
  assert.match(surface, /setWorkspaceBrain\(cached\.snapshot\)[\s\S]*setWorkspaceBrainLoading\(cached\.shouldRefresh\)/)
  assert.match(surface, /\.catch\(\(\) => \{[\s\S]*if \(!cached\) setWorkspaceBrain\(null\)[\s\S]*setWorkspaceBrainLoading\(false\)/)
  assert.match(surface, /learnAwisWorkspaceMemory/)
  assert.match(surface, /recordAwisWorkspaceInteraction/)
  assert.match(surface, /recordAwisWorkspaceMaintenance/)
  assert.match(surface, /saveAwisWorkspaceMemory/)
  assert.match(surface, /buildAwisWorkspaceContextPack/)
  assert.match(surface, /buildAwisWorkspaceProviderCapsule/)
  assert.match(surface, /buildAwisWorkspaceSpaceProjection\(projectSpaceContextPacks\)/)
  assert.match(surface, /buildAwisWorkspaceArtifact\(awisWorkspaceContextPack\)/)
  assert.match(surface, /buildAwisWorkspaceTaskContextProjection/)
  assert.match(surface, /saveAwisWorkspaceArtifact\(artifact\)/)
  assert.match(surface, /persistAwisWorkspaceArtifact\(artifact\)/)
  assert.match(surface, /awisAutoSavedArtifactHashesRef/)
  assert.match(surface, /awisAutoSavedArtifactHashesRef\.current\.has\(artifact\.artifact_hash\)/)
  assert.match(surface, /awisAutoSavedArtifactHashesRef\.current\.add\(artifact\.artifact_hash\)/)
  assert.match(surface, /const handleAwisRefreshFolderMap = useCallback/)
  assert.match(surface, /const rememberAwisMaintenance = useCallback/)
  assert.match(surface, /bridge\.scanWorkspaceBrain\(workspacePath\)/)
  assert.match(surface, /const handleAwisPreserveArtifact = useCallback/)
  assert.match(surface, /action: 'preserve_artifact'/)
  assert.match(surface, /action: 'open_side_by_side'/)
  assert.match(surface, /Ouro AWIS preservado para a próxima conversa/)
  assert.match(surface, /onProjectSpaceContextPacksChange=\{setProjectSpaceContextPacks\}/)
  assert.match(surface, /const \[projectSpaceOutcomeEvent, setProjectSpaceOutcomeEvent\] = useState<LocalProjectSpaceOutcomeEvent \| null>\(null\)/)
  assert.match(surface, /setProjectSpaceOutcomeEvent\(\{[\s\S]*status: traceSucceeded \? 'succeeded' : 'failed'[\s\S]*threadIds: trace\?\.thread_id \? \[trace\.thread_id\] : null[\s\S]*comparisonOpened: channel === 'workbench'/)
  assert.match(surface, /projectSpaceOutcomeEvent=\{projectSpaceOutcomeEvent\}/)
  assert.match(surface, /onProjectSpaceMaintenance=\{rememberAwisMaintenance\}/)
  assert.match(surface, /const buildAwisSendContext = useCallback/)
  assert.match(surface, /providerCapsule \? \[providerCapsule\] : \[\]/)
  assert.match(surface, /conversationContext: sendContext\.conversationContext/)
  assert.match(surface, /registerAwisTraceContext\(trace, 'conversation', sendContext\.taskContext\)/)
  assert.match(useAtlasAi, /const awisMetadata = awisThreadMetadataFromContext\(options\?\.conversationContext\)/)
  assert.match(useAtlasAi, /function awisPlanConstraintsFromContext\(conversationContext\?: unknown\[\]\): string\[\]/)
  assert.match(useAtlasAi, /const awisPlanConstraints = awisPlanConstraintsFromContext\(options\?\.conversationContext\)/)
  assert.match(useAtlasAi, /user_constraints: awisPlanConstraints/)
  assert.match(useAtlasAi, /awis_context_source: 'workspace_provider_capsule'/)
  assert.match(useAtlasAi, /const taskPacket = objectRecord\(providerCapsule\?\.task_packet\)/)
  assert.match(useAtlasAi, /const workspaceRunbook = objectRecord\(contextPack\?\.workspace_runbook\)/)
  assert.match(useAtlasAi, /awis_workspace_runbook: \{[\s\S]*runbook_hash: providerSafeString\(workspaceRunbook\?\.runbook_hash/)
  assert.match(useAtlasAi, /taskPacketLoadFirst\.length \? `AWIS tarefa carregar: \$\{taskPacketLoadFirst\.join\(' \| '\)\}`/)
  assert.match(useAtlasAi, /taskPacketValidation\.length \? `AWIS tarefa validar: \$\{taskPacketValidation\.join\(' \| '\)\}`/)
  assert.match(useAtlasAi, /taskPacketLearningArchive\.length \? `AWIS tarefa arquivar aprendizado: \$\{taskPacketLearningArchive\.join\(' \| '\)\}`/)
  assert.match(useAtlasAi, /const taskPacketAutomationPlan = objectRecord\(taskPacketLearning\?\.automation_plan\)/)
  assert.match(useAtlasAi, /taskPacketAutomationSafe\.length \? `AWIS tarefa automação segura: \$\{taskPacketAutomationSafe\.join\(' \| '\)\}`/)
  assert.match(useAtlasAi, /taskPacketAutomationConfirm\.length \? `AWIS tarefa confirmar primeiro: \$\{taskPacketAutomationConfirm\.join\(' \| '\)\}`/)
  assert.match(useAtlasAi, /taskPacketAutomationObserve\.length \? `AWIS tarefa apenas observar: \$\{taskPacketAutomationObserve\.join\(' \| '\)\}`/)
  assert.match(useAtlasAi, /const continueLearning = objectRecord\(providerCapsule\?\.continue_learning\)/)
  assert.match(useAtlasAi, /const learnedSpaces = strongestSpaces[\s\S]*objectRecord\(space\.learned_memory\)[\s\S]*awis_space_learned_memory: learnedSpaces/)
  assert.match(useAtlasAi, /const twinHashes = objectRecord\(twin\?\.hashes\)/)
  assert.match(useAtlasAi, /const retention = objectRecord\(contextPack\?\.retention\)/)
  assert.match(useAtlasAi, /const startupOrchestration = objectRecord\(contextPack\?\.startup_orchestration\)/)
  assert.match(useAtlasAi, /const automation = objectRecord\(contextPack\?\.automation\)/)
  assert.match(useAtlasAi, /const selfImprovement = objectRecord\(contextPack\?\.self_improvement\)/)
  assert.match(useAtlasAi, /const adaptiveLearning = objectRecord\(contextPack\?\.adaptive_learning_plan\)/)
  assert.match(useAtlasAi, /const providerStrategy = objectRecord\(contextPack\?\.provider_strategy\)/)
  assert.match(useAtlasAi, /const executionDoctrine = objectRecord\(contextPack\?\.execution_doctrine\)/)
  assert.match(useAtlasAi, /const memoryFreshness = objectRecord\(contextPack\?\.memory_freshness\)/)
  assert.match(useAtlasAi, /const learningFlywheel = objectRecord\(contextPack\?\.learning_flywheel\)/)
  assert.match(useAtlasAi, /const launchContract = objectRecord\(contextPack\?\.launch_contract\)/)
  assert.match(useAtlasAi, /const topology = objectRecord\(contextPack\?\.topology\)/)
  assert.match(useAtlasAi, /awis_preflight_gates: preflightGates/)
  assert.match(useAtlasAi, /awis_twin_hashes: \{[\s\S]*genome: providerSafeString\(twinHashes\?\.genome_hash/)
  assert.match(useAtlasAi, /awis_retention: \{[\s\S]*keep_hot: providerSafeStringList\(retentionLifecycle\?\.keep_hot/)
  assert.match(useAtlasAi, /awis_startup_orchestration: \{[\s\S]*launch_mode: providerSafeString\(startupOrchestration\?\.launch_mode/)
  assert.match(useAtlasAi, /awis_automation: \{[\s\S]*maintenance_queue: automationQueue/)
  assert.match(useAtlasAi, /awis_self_improvement: \{[\s\S]*improvement_queue: selfImprovementQueue/)
  assert.match(useAtlasAi, /awis_adaptive_learning: \{[\s\S]*never_automate: providerSafeStringList\(adaptiveHumanControl\?\.never_automate/)
  assert.match(useAtlasAi, /awis_provider_strategy: \{[\s\S]*fallback_order: providerSafeStringList\(providerStrategy\?\.fallback_order/)
  assert.match(useAtlasAi, /awis_execution_doctrine: \{[\s\S]*required_before_execution: providerSafeStringList\(doctrinePreflight\?\.required_before_execution/)
  assert.match(useAtlasAi, /awis_memory_freshness: \{[\s\S]*revalidate: providerSafeStringList\(freshnessEvidence\?\.revalidate/)
  assert.match(useAtlasAi, /awis_confidence: \{[\s\S]*avoid_until_revalidated: providerSafeStringList\(confidencePolicy\?\.avoid_until_revalidated/)
  assert.match(useAtlasAi, /awis_learning_flywheel: \{[\s\S]*next_safe_automations: providerSafeStringList\(flywheelAutomation\?\.next_safe_automations/)
  assert.match(useAtlasAi, /awis_launch_contract: \{[\s\S]*first_load: providerSafeStringList\(launchStartup\?\.first_load/)
  assert.match(useAtlasAi, /awis_topology: \{[\s\S]*test_commands: providerSafeStringList\(topologyExecutionMap\?\.test_commands/)
  assert.match(useAtlasAi, /const componentMemory = objectRecord\(contextPack\?\.component_memory\)/)
  assert.match(useAtlasAi, /const semanticIndex = objectRecord\(contextPack\?\.semantic_index\)/)
  assert.match(useAtlasAi, /const impactMap = objectRecord\(contextPack\?\.impact_map\)/)
  assert.match(useAtlasAi, /const taskRouter = objectRecord\(contextPack\?\.task_router\)/)
  assert.match(useAtlasAi, /const livingGraph = objectRecord\(contextPack\?\.living_graph\)/)
  assert.match(useAtlasAi, /const workspaceMesh = objectRecord\(contextPack\?\.workspace_mesh\)/)
  assert.match(useAtlasAi, /const currentTruthPack = objectRecord\(contextPack\?\.current_truth_pack\)/)
  assert.match(useAtlasAi, /const nextSessionBrain = objectRecord\(contextPack\?\.next_session_brain\)/)
  assert.match(useAtlasAi, /const nextSessionTruthHints = objectRecord\(nextSessionContextLoading\?\.truth_hints\)/)
  assert.match(useAtlasAi, /const repositoryConstellation = objectRecord\(contextPack\?\.repository_constellation\)/)
  assert.match(useAtlasAi, /awis_component_memory: \{[\s\S]*strongest: strongestComponents/)
  assert.match(useAtlasAi, /awis_semantic_index: \{[\s\S]*aliases: semanticAliases/)
  assert.match(useAtlasAi, /awis_task_router: \{[\s\S]*routes: taskRoutes/)
  assert.match(useAtlasAi, /awis_impact_map: \{[\s\S]*component_impacts: impactComponents/)
  assert.match(useAtlasAi, /awis_living_graph: \{[\s\S]*golden_path: providerSafeStringList\(livingGraph\?\.golden_path/)
  assert.match(useAtlasAi, /awis_workspace_mesh: \{[\s\S]*mesh_hash: providerSafeString\(workspaceMesh\?\.mesh_hash/)
  assert.match(useAtlasAi, /awis_current_truth_pack: \{[\s\S]*truth_hash: providerSafeString\(currentTruthPack\?\.truth_hash/)
  assert.match(useAtlasAi, /awis_next_session_truth: \{[\s\S]*brain_hash: providerSafeString\(nextSessionBrain\?\.brain_hash/)
  assert.match(useAtlasAi, /never_load_raw: providerSafeStringList\(nextSessionTruthHints\?\.never_load_raw/)
  assert.match(useAtlasAi, /awis_repository_constellation: \{[\s\S]*constellation_hash: providerSafeString\(repositoryConstellation\?\.constellation_hash/)
  assert.match(useAtlasAi, /const spaces = objectRecord\(contextPack\?\.spaces\)/)
  assert.match(useAtlasAi, /const projectedStrongSpaces = arrayRecords\(spaces\?\.strongest_spaces\)/)
  assert.match(useAtlasAi, /const recommendedSpaceBrain = arrayRecords\(recommendedContext\?\.space_brain\)/)
  assert.match(useAtlasAi, /const spaceLearnedSignals = providerSafeStringList\(projectedStrongSpaces\.flatMap/)
  assert.match(useAtlasAi, /const spaceLearnedOutcomes = projectedStrongSpaces/)
  assert.match(useAtlasAi, /AWIS Spaces ativos: \$\{activeSpaces\.join\(' \| '\)\}/)
  assert.match(useAtlasAi, /AWIS Space Brain: \$\{strongestSpaces\.join\(' \| '\)\}/)
  assert.match(useAtlasAi, /AWIS Space carregar: \$\{spaceLoadFirst\.join\(' \| '\)\}/)
  assert.match(useAtlasAi, /AWIS Space continuar: \$\{spaceCarryForward\.join\(' \| '\)\}/)
  assert.match(useAtlasAi, /AWIS Space validar: \$\{spaceValidate\.join\(' \| '\)\}/)
  assert.match(useAtlasAi, /AWIS Space aprendeu: \$\{spaceLearnedSignals\.join\(' \| '\)\}/)
  assert.match(useAtlasAi, /AWIS Space outcomes: \$\{spaceLearnedOutcomes\.join\(' \| '\)\}/)
  assert.match(useAtlasAi, /AWIS automação antes do envio: \$\{automationBeforeSend\.join\(' \| '\)\}/)
  assert.match(useAtlasAi, /AWIS automação depois do envio: \$\{automationAfterSend\.join\(' \| '\)\}/)
  assert.match(useAtlasAi, /AWIS melhoria fila: \$\{selfImprovementQueue\.join\(' \| '\)\}/)
  assert.match(useAtlasAi, /AWIS melhoria validar: \$\{selfImprovementValidate\.join\(' \| '\)\}/)
  assert.match(useAtlasAi, /AWIS adaptativo antes do envio: \$\{adaptiveBeforeSend\.join\(' \| '\)\}/)
  assert.match(useAtlasAi, /AWIS adaptativo pontes repo: \$\{adaptiveCrossRepo\.join\(' \| '\)\}/)
  assert.match(useAtlasAi, /AWIS nunca automatizar: \$\{adaptiveNeverAutomate\.join\(' \| '\)\}/)
  assert.match(useAtlasAi, /AWIS provider preferir: \$\{providerPreferences\.join\(' \| '\)\}/)
  assert.match(useAtlasAi, /AWIS doutrina antes de executar: \$\{doctrineRequired\.join\(' \| '\)\}/)
  assert.match(useAtlasAi, /AWIS frescor revalidar: \$\{freshnessRevalidate\.join\(' \| '\)\}/)
  assert.match(useAtlasAi, /AWIS confiança evitar até revalidar: \$\{confidenceAvoid\.join\(' \| '\)\}/)
  assert.match(useAtlasAi, /AWIS flywheel automações seguras: \$\{flywheelSafeAutomation\.join\(' \| '\)\}/)
  assert.match(useAtlasAi, /AWIS contrato de partida carregar: \$\{launchFirstLoad\.join\(' \| '\)\}/)
  assert.match(useAtlasAi, /AWIS topologia testes: \$\{topologyTests\.join\(' \| '\)\}/)
  assert.match(useAtlasAi, /AWIS aprender depois: \$\{learningActions\.join\(' \| '\)\}/)
  assert.match(useAtlasAi, /AWIS próxima sessão carregar: \$\{nextSessionFirstLoad\.join\(' \| '\)\}/)
  assert.match(useAtlasAi, /awis_task_feedback_loop/)
  assert.match(useAtlasAi, /AWIS feedback registrar: \$\{feedbackRecord\.join\(' \| '\)\}/)
  assert.match(useAtlasAi, /AWIS feedback Spaces: \$\{feedbackSpaces\.join\(' \| '\)\}/)
  assert.match(useAtlasAi, /AWIS feedback relações: \$\{feedbackRelations\.join\(' \| '\)\}/)
  assert.match(useAtlasAi, /AWIS feedback mesh: \$\{feedbackMesh\.join\(' \| '\)\}/)
  assert.match(useAtlasAi, /const contextKernel = objectRecord\(contextPack\?\.context_kernel\)/)
  assert.match(useAtlasAi, /const preflight = objectRecord\(contextPack\?\.preflight\)/)
  assert.match(useAtlasAi, /const workspaceTwin = objectRecord\(contextPack\?\.workspace_twin\)/)
  assert.match(useAtlasAi, /const retention = objectRecord\(contextPack\?\.retention\)/)
  assert.match(useAtlasAi, /const startupOrchestration = objectRecord\(contextPack\?\.startup_orchestration\)/)
  assert.match(useAtlasAi, /AWIS kernel carregar primeiro: \$\{kernelPriorityLoad\.join\(' \| '\)\}/)
  assert.match(useAtlasAi, /AWIS pré-voo: \$\{preflightMode\}/)
  assert.match(useAtlasAi, /AWIS gates: \$\{preflightGates\.join\(' \| '\)\}/)
  assert.match(useAtlasAi, /AWIS twin hashes: \$\{twinHashes\.join\(' \| '\)\}/)
  assert.match(useAtlasAi, /AWIS manter quente: \$\{retentionKeepHot\.join\(' \| '\)\}/)
  assert.match(useAtlasAi, /AWIS sequência de partida: \$\{startupSequence\.join\(' \| '\)\}/)
  assert.match(useAtlasAi, /AWIS componentes carregar: \$\{componentLoadFirst\.join\(' \| '\)\}/)
  assert.match(useAtlasAi, /AWIS índice semântico: \$\{semanticAliases\.join\(' \| '\)\}/)
  assert.match(useAtlasAi, /AWIS rotas aprendidas: \$\{taskRoutes\.join\(' \| '\)\}/)
  assert.match(useAtlasAi, /AWIS grafo caminho ouro: \$\{livingGoldenPath\.join\(' \| '\)\}/)
  assert.match(useAtlasAi, /AWIS mesh carregar: \$\{meshLoadOrder\.join\(' \| '\)\}/)
  assert.match(useAtlasAi, /AWIS verdade manter: \$\{truthKeep\.join\(' \| '\)\}/)
  assert.match(useAtlasAi, /AWIS truth carregar: \$\{truthLoadFirst\.join\(' \| '\)\}/)
  assert.match(useAtlasAi, /AWIS repositórios carregar: \$\{repoLoadFirst\.join\(' \| '\)\}/)
  assert.match(useAtlasAi, /AWIS impacto validar: \$\{impactValidation\.join\(' \| '\)\}/)
  assert.match(useAtlasAi, /\)\)\.slice\(0, 120\)/)
  assert.match(useAtlasAi, /const replayContract = objectRecord\(memoryConsolidation\?\.replay_contract\)/)
  assert.match(useAtlasAi, /awis_replay_contract/)
  assert.match(useAtlasAi, /AWIS replay carregar: \$\{replayLoadFirst\.join\(' \| '\)\}/)
  assert.match(useAtlasAi, /AWIS replay validar: \$\{replayValidate\.join\(' \| '\)\}/)
  assert.match(useAtlasAi, /AWIS runbook iniciar: \$\{runbookStartHere\.join\(' \| '\)\}/)
  assert.match(useAtlasAi, /AWIS runbook carregar: \$\{runbookLoadFirst\.join\(' \| '\)\}/)
  assert.match(useAtlasAi, /AWIS runbook validar: \$\{runbookValidate\.join\(' \| '\)\}/)
  assert.match(useAtlasAi, /AWIS runbook recuperar: \$\{runbookRetry\.join\(' \| '\)\}/)
  assert.match(useAtlasAi, /AWIS workspaces relacionados: \$\{transferHints\.join\(' \| '\)\}/)
  assert.match(useAtlasAi, /AWIS transferir só abstrações: \$\{transferReuse\.join\(' \| '\)\}/)
  assert.match(useAtlasAi, /AWIS revalidar transferência: \$\{transferValidate\.join\(' \| '\)\}/)
  assert.match(useAtlasAi, /AWIS nunca transferir: \$\{transferNever\.join\(' \| '\)\}/)
  assert.match(useAtlasAi, /const continuityHandoff = objectRecord\(providerCapsule\?\.continuity_handoff\)/)
  assert.match(useAtlasAi, /awis_continuity_handoff/)
  assert.match(useAtlasAi, /AWIS retomar primeiro: \$\{handoffRestore\.join\(' \| '\)\}/)
  assert.match(useAtlasAi, /AWIS handoff carregar: \$\{handoffLoad\.join\(' \| '\)\}/)
  assert.match(useAtlasAi, /AWIS handoff validar: \$\{handoffValidate\.join\(' \| '\)\}/)
  assert.match(useAtlasAi, /AWIS artifacts ativos: \$\{handoffArtifacts\.join\(' \| '\)\}/)
  assert.match(useAtlasAi, /AWIS limites humanos: \$\{handoffBoundary\.join\(' \| '\)\}/)
  assert.match(useAtlasAi, /AWIS recuperação rebaixar: \$\{recoveryDemote\.join\(' \| '\)\}/)
  assert.match(useAtlasAi, /awis_folder_focus[\s\S]*awis_evidence_gate[\s\S]*awis_next_session_contract/)
  assert.match(useAtlasAi, /awis_context_refreshed_at: new Date\(\)\.toISOString\(\)/)
  assert.match(useAtlasAi, /existingThreadIdBeforeSend && Object\.keys\(awisMetadataForThread\)\.length > 0/)
  assert.match(useAtlasAi, /await updateAiThread\(existingThreadIdBeforeSend, \{[\s\S]*metadata: refreshedMetadata/)
  assert.match(useAtlasAi, /Metadata AWIS melhora continuidade, mas não deve bloquear o envio\./)
  assert.match(surface, /atlas\.lastTerminalTrace/)
  assert.match(surface, /const AWIS_PENDING_TRACE_CONTEXT_STORAGE = 'atlas-desktop:atlas-ai-pending-trace-contexts'/)
  assert.match(surface, /function providerSafePendingTaskContext[\s\S]*\/Users\\\//)
  assert.match(surface, /function providerSafePendingTaskContext[\s\S]*thread_id\|source_thread_ids\|operator_input\|response_text\|raw\[_ \]conversation\|full\[_ \]message/)
  assert.match(threadList, /function safeProviderText[\s\S]*thread_id\|source_thread_ids\|operator_input\|response_text\|raw\[_ \]conversation\|full\[_ \]message/)
  assert.match(surface, /saveAwisPendingTraceContext\(trace\.id, context\)/)
  assert.match(surface, /const persistedContext = takeAwisPendingTraceContext\(trace\.id\)[\s\S]*const context = awisPendingTraceContextsRef\.current\.get\(trace\.id\) \?\? persistedContext/)
  assert.match(surface, /rememberAwisInteraction\(context\?\.channel \?\? 'conversation', trace, context\?\.taskContext \?\? null\)/)
  assert.match(surface, /let nextMemory = recordAwisWorkspaceMaintenance\(update\.memory, \{[\s\S]*action: 'record_outcome'[\s\S]*outcome real registrado automaticamente/)
  assert.match(surface, /validationMaintenanceCommands[\s\S]*action: traceSucceeded \? 'promote_command' : 'revalidate_command'/)
  assert.match(surface, /comando validou outcome real e pode subir no contexto inicial/)
  assert.match(surface, /outcome falhou; comando precisa nova evidência antes de virar ouro/)
  assert.match(surface, /transferContract\?\.workspace_hints[\s\S]*action: 'transfer_learning'/)
  assert.match(surface, /contrato entre workspaces usado em outcome real/)
  assert.match(surface, /transferência entre workspaces precisa revalidação antes de virar ouro/)
  assert.match(surface, /transferContract\?\.reuse\[0\] \? `reuso:\$\{transferContract\.reuse\[0\]\}` : null/)
  assert.match(surface, /transferContract\?\.validate_before_use\[0\] \? `revalidar:\$\{transferContract\.validate_before_use\[0\]\}` : null/)
  assert.match(surface, /transferContract\?\.never_transfer\[0\] \? `bloqueio:\$\{transferContract\.never_transfer\[0\]\}` : null/)
  assert.match(surface, /const continuityLabels = awisWorkspaceContextPack\?\.continuity/)
  assert.match(surface, /const handoffLabels = awisWorkspaceContextPack\?\.handoff_pack/)
  assert.match(surface, /const artifactReplayLabels = awisWorkspaceContextPack\?\.artifact_replay/)
  assert.match(surface, /const evidenceGateLabels = taskContext/)
  assert.match(surface, /const nextSessionLabels = taskContext/)
  assert.match(surface, /const recoveryLabels = taskContext/)
  assert.match(surface, /const adaptiveLearningLabels = awisWorkspaceContextPack\?\.adaptive_learning_plan/)
  assert.match(surface, /const componentMemoryLabels = awisWorkspaceContextPack\?\.component_memory/)
  assert.match(surface, /const semanticIndexLabels = awisWorkspaceContextPack\?\.semantic_index/)
  assert.match(surface, /const taskRouterLabels = awisWorkspaceContextPack\?\.task_router/)
  assert.match(surface, /const impactMapLabels = awisWorkspaceContextPack\?\.impact_map/)
  assert.match(surface, /const livingGraphLabels = awisWorkspaceContextPack\?\.living_graph/)
  assert.match(surface, /const workspaceMeshLabels = awisWorkspaceContextPack\?\.workspace_mesh/)
  assert.match(surface, /const truthPackLabels = awisWorkspaceContextPack\?\.current_truth_pack/)
  assert.match(surface, /const repositoryConstellationLabels = awisWorkspaceContextPack\?\.repository_constellation/)
  assert.match(surface, /const providerStrategyLabels = awisWorkspaceContextPack\?\.provider_strategy/)
  assert.match(surface, /const executionDoctrineLabels = awisWorkspaceContextPack\?\.execution_doctrine/)
  assert.match(surface, /const memoryFreshnessLabels = awisWorkspaceContextPack\?\.memory_freshness/)
  assert.match(surface, /const confidenceLabels = awisWorkspaceContextPack\?\.confidence/)
  assert.match(surface, /const learningFlywheelLabels = awisWorkspaceContextPack\?\.learning_flywheel/)
  assert.match(surface, /const launchContractLabels = awisWorkspaceContextPack\?\.launch_contract/)
  assert.match(surface, /const topologyLabels = awisWorkspaceContextPack\?\.topology/)
  assert.match(surface, /const runbookLabels = awisWorkspaceContextPack\?\.workspace_runbook/)
  assert.match(surface, /continuityLabels,\s*[\s\S]*handoffLabels,\s*[\s\S]*artifactReplayLabels,\s*[\s\S]*evidenceGateLabels,\s*[\s\S]*nextSessionLabels,\s*[\s\S]*recoveryLabels,\s*[\s\S]*adaptiveLearningLabels,[\s\S]*componentMemoryLabels,[\s\S]*semanticIndexLabels,[\s\S]*taskRouterLabels,[\s\S]*impactMapLabels,[\s\S]*livingGraphLabels,[\s\S]*workspaceMeshLabels,[\s\S]*truthPackLabels,[\s\S]*repositoryConstellationLabels,/)
  assert.match(surface, /runbookLabels,\s*[\s\S]*providerStrategyLabels,\s*[\s\S]*executionDoctrineLabels,\s*[\s\S]*memoryFreshnessLabels,\s*[\s\S]*confidenceLabels,\s*[\s\S]*learningFlywheelLabels,\s*[\s\S]*launchContractLabels,\s*[\s\S]*topologyLabels,/)
  assert.match(surface, /const structuralOutcomeLabels: Array<\{[\s\S]*kind: string[\s\S]*labels: string\[\] \| null[\s\S]*\}> = \[/)
  assert.match(surface, /component-memory[\s\S]*semantic-index[\s\S]*task-router[\s\S]*impact-map[\s\S]*living-graph[\s\S]*workspace-mesh[\s\S]*truth-pack[\s\S]*repository-constellation/)
  assert.match(surface, /workspace-runbook[\s\S]*provider-strategy[\s\S]*execution-doctrine[\s\S]*memory-freshness[\s\S]*confidence[\s\S]*learning-flywheel[\s\S]*launch-contract[\s\S]*topology/)
  assert.match(surface, /item\.kind\} usado em outcome real e pode reforçar próxima sessão/)
  assert.match(memory, /componentMemoryLabels: string\[\]/)
  assert.match(memory, /semanticIndexLabels: string\[\]/)
  assert.match(memory, /taskRouterLabels: string\[\]/)
  assert.match(memory, /impactMapLabels: string\[\]/)
  assert.match(memory, /livingGraphLabels: string\[\]/)
  assert.match(memory, /workspaceMeshLabels: string\[\]/)
  assert.match(memory, /truthPackLabels: string\[\]/)
  assert.match(memory, /repositoryConstellationLabels: string\[\]/)
  assert.match(memory, /runbookLabels\?: string\[\]/)
  assert.match(memory, /component-memory:\$\{label\}/)
  assert.match(memory, /repository-constellation:\$\{label\}/)
  assert.match(memory, /runbook:\$\{label\}/)
  assert.match(memory, /stack_dependency_signals/)
  assert.match(memory, /const languageSignals = unique\(\(brain\.languages \?\? \[\]\)/)
  assert.match(memory, /\.\.\.languageSignals,[\s\S]*\.\.\.\(brain\.signals \?\? \[\]\),[\s\S]*\.\.\.languageWeightSignals/)
  assert.match(memory, /topologyStackSignals\.slice\(0, 5\)\.map\(\(signal\) => `stack:\$\{signal\}`\)/)
  assert.match(memory, /knowledge_map\.stack_dependency_signals\.filter\(\(signal\) => !signal\.startsWith\('linguagem:'\)\)/)
  assert.match(memory, /internal_dependency_edges/)
  assert.match(memory, /workspace_members: string\[\]/)
  assert.match(memory, /workspace_dependency_edges: string\[\]/)
  assert.match(memory, /monorepo-member:\$\{member\}/)
  assert.match(memory, /monorepo-edge:\$\{edge\}/)
  assert.match(memory, /dependency_edges: string\[\]/)
  assert.match(memory, /selectTaskDependencyEdges/)
  assert.match(memory, /command_intents: string\[\]/)
  assert.match(memory, /command_lanes: \{/)
  assert.match(memory, /commandIntentForCommand/)
  assert.match(memory, /selectTaskCommandIntents/)
  assert.match(memory, /buildTaskCommandLanes/)
  assert.match(memory, /command_lanes: commandLanes/)
  assert.match(memory, /command_lanes: input\.commandLanes/)
  assert.match(memory, /mergeAwisWorkspaceCommandLanes/)
  assert.match(memory, /command-lane:auto:\$\{command\}/)
  assert.match(memory, /recommended_context\.dependency_edges/)
  assert.match(memory, /command_intents: commandIntents/)
  assert.match(memory, /command_lanes: commandLanes/)
  assert.match(memory, /const providerCommandLanes =[\s\S]*taskContext\?\.recommended_context\.command_lanes[\s\S]*pack\.artifact_replay\?\.cold_start_seed\.command_lanes/)
  assert.match(memory, /command_lanes: providerCommandLanes/)
  assert.match(memory, /dependency-edge:\$\{edge\}/)
  assert.match(memory, /command-intent:\$\{intent\}/)
  assert.match(memory, /folder_dependency_edges/)
  assert.match(memory, /folder-dependency:\$\{edge\}/)
  assert.match(memory, /folder_command_intents/)
  assert.match(memory, /folder-command-intent:\$\{intent\}/)
  assert.match(contract, /dependency_edges: recommendedDependencyEdges/)
  assert.match(contract, /workspace_members: topologyWorkspaceMembers/)
  assert.match(contract, /workspace_dependency_edges: topologyWorkspaceDependencyEdges/)
  assert.match(contract, /command_intents: recommendedCommandIntents/)
  assert.match(contract, /command_lanes: \{/)
  assert.match(contract, /compactObjectRecord\(providerCapsule\?\.command_lanes\)/)
  assert.match(useAtlasAi, /awis_dependency_edges: recommendedDependencyEdges/)
  assert.match(useAtlasAi, /awis_workspace_members: topologyWorkspaceMembers/)
  assert.match(useAtlasAi, /awis_workspace_dependency_edges: topologyWorkspaceDependencyEdges/)
  assert.match(useAtlasAi, /awis_command_intents: recommendedCommandIntents/)
  assert.match(useAtlasAi, /awis_command_lanes: \{/)
  assert.match(useAtlasAi, /objectRecord\(providerCapsule\?\.command_lanes\)/)
  assert.match(useAtlasAi, /AWIS dependências reais/)
  assert.match(useAtlasAi, /AWIS monorepo membros/)
  assert.match(useAtlasAi, /AWIS monorepo edges/)
  assert.match(useAtlasAi, /AWIS intenção de comandos/)
  assert.match(useAtlasAi, /AWIS auto-validar/)
  assert.match(useAtlasAi, /AWIS confirmar antes de rodar/)
  assert.match(memory, /stack-signal:\$\{signal\}/)
  assert.match(memory, /folder_stack_signals/)
  assert.match(memory, /folder-stack:\$\{signal\}/)
  assert.match(surface, /compactAwisEvidence\(\[[\s\S]*status:\$\{status\}[\s\S]*canal:\$\{channel\}/)
  assert.match(surface, /const shouldPreserveOutcomeArtifact = awisTraceSucceeded\(trace\) && Boolean\([\s\S]*taskContext\?\.learning_hooks\.next_session_contract\.preserve_as_artifact/)
  assert.match(surface, /const outcomeTaskPacket = buildAwisWorkspaceProviderCapsule\(awisWorkspaceContextPack, taskContext\)\?\.task_packet \?\? null/)
  assert.match(surface, /outcomeTaskPacket\.context\.space_brain\.slice\(0, 2\)\.flatMap/)
  assert.match(surface, /kind: 'task-packet', labels: taskPacketLabels/)
  assert.match(surface, /taskPacketLabels,[\s\S]*runbookLabels,[\s\S]*providerStrategyLabels/)
  assert.match(surface, /const outcomeContextPack = buildAwisWorkspaceContextPack\(\{[\s\S]*memory: nextMemory[\s\S]*evolution: nextEvolution[\s\S]*relations: nextRelations/)
  assert.match(surface, /const outcomeArtifact = shouldPreserveOutcomeArtifact[\s\S]*\? buildAwisWorkspaceArtifact\(outcomeContextPack\)[\s\S]*: null/)
  assert.match(surface, /setProjectSpaceOutcomeEvent\(\{[\s\S]*artifactRefs: compactAwisEvidence\(\[[\s\S]*outcomeArtifact\?\.artifact_hash \?\? null/)
  assert.match(surface, /preserveAwisArtifactIfNeeded\(\{[\s\S]*pack: outcomeContextPack/)
  assert.match(surface, /preserveAwisArtifactIfNeeded\(\{[\s\S]*artifact AWIS preservado após outcome real bem-sucedido/)
  assert.match(surface, /interface AwisPendingFolderArtifactRequest/)
  assert.match(surface, /const \[pendingFolderArtifactRequest, setPendingFolderArtifactRequest\] = useState<AwisPendingFolderArtifactRequest \| null>\(null\)/)
  assert.match(surface, /const folderEvidence = compactAwisEvidence\(\[[\s\S]*`\$\{workspaceBrain\.filesSeen\} arquivos`[\s\S]*workspaceBrain\.docDigests\?\.\[0\]\?\.path[\s\S]*workspaceBrain\.dependencyEdges\?\.\[0\]/)
  assert.match(surface, /if \(update\.learned\.length > 0 \|\| update\.changed\.length > 0\) \{[\s\S]*setPendingFolderArtifactRequest\(\{[\s\S]*key: learningKey,[\s\S]*memory: update\.memory,[\s\S]*evidence: folderEvidence/)
  assert.match(surface, /const folderContextPack = buildAwisWorkspaceContextPack\(\{[\s\S]*brain: workspaceBrain,[\s\S]*memory: pendingFolderArtifactRequest\.memory[\s\S]*preserveAwisArtifactIfNeeded\(\{[\s\S]*artifact AWIS preservado após mapa local aprender/)
  assert.match(surface, /persistAwisWorkspaceMemory\(nextMemory\)/)
  assert.match(surface, /workspaceBrainLoading/)
  assert.match(surface, /workspaceBrain,[\s\S]*workspaceMemory,[\s\S]*workspaceLearning: awisWorkspaceContextPack\?\.learning \?\? null/)
  assert.doesNotMatch(surface, /workspaceBrain: workspaceBrainLoading \? null : workspaceBrain/)
  assert.match(threadList, /bridge\.loadAwisProjectSpacesStore\(\)/)
  assert.match(threadList, /mergeLocalProjectSpaces/)
  assert.match(threadList, /mergeLocalSavedProjectSpaceReceipts/)
  assert.match(threadList, /nativeProjectSpacesSaveTailRef/)
  assert.match(threadList, /bridge\.saveAwisProjectSpacesStore\(spacesSnapshot, receiptsSnapshot\)/)
  assert.match(threadList, /nativeProjectSpacesHydrated/)
  assert.match(threadList, /onProjectSpaceMaintenance\?: \(input: \{[\s\S]*action: 'update_space_pack' \| 'open_side_by_side'/)
  assert.match(threadList, /onProjectSpaceMaintenance\?\.\(\{/)
  assert.match(threadList, /action: 'update_space_pack'/)
  assert.match(threadList, /reason: source === 'suggested'[\s\S]*: 'conversas agrupadas em Space'/)
  assert.match(threadList, /onProjectSpaceMaintenance\?\.\(\{[\s\S]*action: 'open_side_by_side'[\s\S]*reason: 'Space aberto para comparar sessões'/)
  assert.match(memory, /atlas\.awis\.workspace_learning_flywheel_projection\.v1/)
  assert.match(memory, /learning_flywheel: AwisWorkspaceLearningFlywheelProjection \| null/)
  assert.match(memory, /learning_flywheel_projection: AwisWorkspaceLearningFlywheelProjection \| null/)
  assert.match(memory, /buildAwisWorkspaceLearningFlywheelProjection/)
  assert.match(memory, /compounding_score/)
  assert.match(memory, /next_safe_automations/)
  assert.match(memory, /update_after_send/)
  assert.match(memory, /flywheel:/)
  assert.match(memory, /atlas\.awis\.workspace_adaptive_learning_plan_projection\.v1/)
  assert.match(memory, /adaptive_learning_plan: AwisWorkspaceAdaptiveLearningPlanProjection \| null/)
  assert.match(memory, /adaptive_learning_plan_projection: AwisWorkspaceAdaptiveLearningPlanProjection \| null/)
  assert.match(memory, /buildAwisWorkspaceAdaptiveLearningPlanProjection/)
  assert.match(memory, /autonomous_cycle/)
  assert.match(memory, /context_economy/)
  assert.match(memory, /repository_compounding/)
  assert.match(memory, /never_automate/)
})

test('AWIS command center surfaces living brain signals without raw projection names', () => {
  assert.match(surface, /workspaceContinuity=\{awisWorkspaceContextPack\?\.continuity \?\? null\}/)
  assert.match(surface, /workspaceAutomation=\{awisWorkspaceContextPack\?\.automation \?\? null\}/)
  assert.match(surface, /workspaceConfidence=\{awisWorkspaceContextPack\?\.confidence \?\? null\}/)
  assert.match(surface, /workspaceLivingGraph=\{awisWorkspaceContextPack\?\.living_graph \?\? null\}/)
  assert.match(surface, /workspaceRelations=\{workspaceRelations\}/)
  assert.match(surface, /workspacePreflight=\{awisWorkspaceContextPack\?\.preflight \?\? null\}/)
  assert.match(surface, /workspaceTwin=\{awisWorkspaceContextPack\?\.workspace_twin \?\? null\}/)
  assert.match(surface, /workspaceLaunchContract=\{awisWorkspaceContextPack\?\.launch_contract \?\? null\}/)
  assert.match(surface, /workspaceMemoryConsolidation=\{awisWorkspaceContextPack\?\.memory_consolidation \?\? null\}/)
  assert.match(surface, /const effectiveWorkspaceNextSessionBrain =[\s\S]*workspaceNextSessionBrain \?\? awisWorkspaceContextPack\?\.next_session_brain \?\? null/)
  assert.match(surface, /workspaceNextSessionBrain=\{effectiveWorkspaceNextSessionBrain\}/)
  assert.match(surface, /workspaceHandoffPack=\{workspaceHandoffPack\}/)
  assert.match(surface, /onRefreshFolderMap=\{handleAwisRefreshFolderMap\}/)
  assert.match(surface, /onPreserveArtifact=\{handleAwisPreserveArtifact\}/)
  assert.match(surface, /onRecordMaintenance=\{rememberAwisMaintenance\}/)
  assert.match(surface, /workspaceConfidence: AwisWorkspaceConfidenceProjection \| null/)
  assert.match(surface, /workspaceLivingGraph: AwisWorkspaceLivingGraphProjection \| null/)
  assert.match(surface, /workspaceRelations: AwisWorkspaceRelationProjection \| null/)
  assert.match(surface, /workspacePreflight: AwisWorkspacePreflightProjection \| null/)
  assert.match(surface, /workspaceTwin: AwisWorkspaceTwinProjection \| null/)
  assert.match(surface, /workspaceLaunchContract: AwisWorkspaceLaunchContractProjection \| null/)
  assert.match(surface, /workspaceMemoryConsolidation: AwisWorkspaceMemoryConsolidationProjection \| null/)
  assert.match(surface, /workspaceNextSessionBrain: AwisWorkspaceNextSessionBrainProjection \| null/)
  assert.match(surface, /workspaceHandoffPack: AwisWorkspaceHandoffProjection \| null/)
  assert.match(surface, /const confidenceLeader = workspaceConfidence/)
  assert.match(surface, /const continuityLeader = workspaceContinuity\?\.restore_priority\[0\] \?\? null/)
  assert.match(surface, /const maintenanceLeader = workspaceAutomation\?\.maintenance_queue\[0\] \?\? null/)
  assert.match(surface, /const connectionLeader = workspaceRelations\?\.connection_contracts\[0\] \?\? null/)
  assert.match(surface, /const awisTransferSignals = \(workspaceRelations\?\.transfer_matrix \?\? \[\]\)/)
  assert.match(surface, /const compactOperationalMaintenance = Array\.from/)
  assert.match(surface, /const operationalLearningSignals = compactOperationalMaintenance/)
  assert.match(surface, /const memoryConsolidationSignals = workspaceMemoryConsolidation \? \[/)
  assert.match(surface, /workspaceMemoryConsolidation\.consolidate\.promote_to_gold\[0\]/)
  assert.match(surface, /workspaceMemoryConsolidation\.consolidate\.revalidate\[0\]/)
  assert.match(surface, /workspaceMemoryConsolidation\.consolidate\.never_promote\[0\]/)
  assert.match(surface, /workspaceMemoryConsolidation\.consolidate\.archive_as_artifact\[0\]/)
  assert.match(surface, /readableAwisMaintenanceAction/)
  assert.match(surface, /readableConsolidationValue/)
  assert.match(surface, /replace\(\/\^awis-\[a-z0-9-\]\+\$\/i, 'snapshot AWIS'\)/)
  assert.match(surface, /replace\(\/\^manutenção:preserve_artifact:\/, 'Ouro salvo: '\)/)
  assert.match(surface, /replace\(\/\\bpreserve_artifact\\b\/g, 'salvar ouro'\)/)
  assert.match(surface, /replace\(\/\\bupdate_space_pack\\b\/g, 'fortalecer Space'\)/)
  assert.match(surface, /readableAwisQueueValue/)
  assert.match(surface, /replace\(\/\^space-brain:\/, 'Space Brain: '\)/)
  assert.match(surface, /const readableTransferValue = \(value: string\) => value/)
  assert.match(surface, /replace\(\/\^fresco:\/, ''\)/)
  assert.match(surface, /replace\(\/\^validar comando antes de aplicar:\/, 'validar comando '\)/)
  assert.match(surface, /replace\(\/\^linguagem:\/, 'stack '\)/)
  assert.match(surface, /startupLoadLabel \? readableTransferValue\(startupLoadLabel\) : 'memória pronta'/)
  assert.match(surface, /const awisLivingQueue = \[/)
  assert.match(surface, /recordCommandCenterMaintenance/)
  assert.match(surface, /nextAction: \(\(\) => Promise<boolean \| void> \| boolean \| void\) \| null/)
  assert.match(surface, /status: result === false \? 'failed' : 'succeeded'/)
  assert.match(surface, /status: 'skipped'[\s\S]*sem ação executável/)
  assert.match(surface, /status: 'failed'[\s\S]*erro ao executar ação/)
  assert.match(surface, /const handleAwisPreserveArtifact = useCallback\(\(\): boolean =>/)
  assert.match(surface, /maintenanceLeader\.action,[\s\S]*maintenanceLeader\.label,[\s\S]*maintenanceLeader\.reason/)
  assert.match(surface, /'cross_workspace_transfer'[\s\S]*connectionLeader\.workspace_hint/)
  assert.match(surface, /'revalidate_context'[\s\S]*workspaceRetention\.lifecycle\.revalidate\[0\][\s\S]*workspaceRetention\.policy\.reason[\s\S]*\['retenção AWIS', workspaceRetention\.policy\.mode\][\s\S]*onPreserveArtifact/)
  assert.match(surface, /actionLabel: maintenanceLeader\.action === 'refresh_folder_map'/)
  assert.match(surface, /onAction: maintenanceLeader\.action === 'refresh_folder_map'/)
  assert.match(surface, /const graphLeader = workspaceLivingGraph/)
  assert.match(surface, /const preflightBlockingGate = workspacePreflight/)
  assert.match(surface, /const twinPrimaryComponent = workspaceTwin/)
  assert.match(surface, /const launchPrimaryLoad = workspaceLaunchContract/)
  assert.match(surface, /launchMaintenance/)
  assert.match(surface, /confidence-fallback/)
  assert.match(surface, /continuity-fallback/)
  assert.match(surface, /maintenance-fallback/)
  assert.match(surface, /aria-label="Sinais vivos do AWIS"/)
  assert.match(surface, /aria-label="Fila viva AWIS"/)
  assert.match(surface, /aria-label="Aprendizado entre workspaces"/)
  assert.match(surface, /aria-label="Aprendizado operacional recente"/)
  assert.match(surface, /aria-label="Ouro e revisão AWIS"/)
  assert.match(surface, /atlas-ai-awis-transfer-card/)
  assert.match(surface, /atlas-ai-awis-learning-card/)
  assert.match(surface, /atlas-ai-awis-consolidation-card/)
  assert.match(surface, /Ouro/)
  assert.match(surface, /Não promover/)
  assert.match(surface, /Artefato/)
  assert.match(surface, /memória reutilizável/)
  assert.match(surface, /AWIS aprendeu/)
  assert.match(surface, /Revalidar/)
  assert.match(surface, /item\.actionLabel && item\.onAction/)
  assert.match(surface, /Confiança/)
  assert.match(surface, /Continuidade/)
  assert.match(surface, /Manter vivo/)
  assert.match(surface, /Repos conectados/)
  assert.match(surface, /Aprendizado entre workspaces/)
  assert.match(surface, /salvar ouro/)
  assert.match(surface, /reusar só com validação local/)
  assert.match(surface, /Pré-checagem/)
  assert.match(surface, /Mapa vivo/)
  assert.match(surface, /Partida viva/)
  assert.match(surface, /Handoff/)
  assert.match(surface, /Partida/)
  assert.match(surface, /pré-checagem pronta/)
  assert.match(surface, /mapa vivo do projeto/)
  assert.match(surface, /partida viva/)
  assert.match(surface, /partida com memória/)
  assert.match(surface, /handoff seguro/)
  assert.doesNotMatch(surface, /workspace_confidence_projection|workspace_continuity_projection|workspace_automation_projection|workspace_preflight_projection|workspace_twin_projection|workspace_launch_contract_projection|genome_hash/)
})

test('AWIS safe automation queue performs only local provider-safe maintenance', () => {
  assert.match(
    surface,
    /const AWIS_SAFE_AUTOMATIC_MAINTENANCE_ACTIONS = new Set<AwisWorkspaceMaintenanceAction>\(\[[\s\S]*'preserve_artifact'[\s\S]*'replay_artifacts'[\s\S]*'update_space_pack'[\s\S]*\]\)/,
    'Only local artifact replay, artifact preservation and Space pack refresh may run automatically.',
  )
  assert.match(
    surface,
    /const awisAutoMaintenanceKeysRef = useRef\(new Set<string>\(\)\)/,
    'Automatic maintenance must be deduplicated so the living loop does not spam memory.',
  )
  assert.match(
    surface,
    /const automation = awisWorkspaceContextPack\.automation[\s\S]*const selfImprovement = awisWorkspaceContextPack\.self_improvement[\s\S]*automation\?\.maintenance_queue \?\? \[\][\s\S]*\.filter\(\(item\) => !item\.requires_human_confirmation\)[\s\S]*selfImprovement\?\.improvement_queue \?\? \[\][\s\S]*!selfImprovement\?\.next_review\.human_confirmation_required[\s\S]*AWIS_SAFE_AUTOMATIC_MAINTENANCE_ACTIONS\.has\(item\.action\)/,
    'The automatic loop must refuse any queued item that asks for human confirmation or is not in the safe local allowlist.',
  )
  assert.match(
    surface,
    /if \(item\.action === 'replay_artifacts'\) \{[\s\S]*if \(!workspaceArtifactReplay\) continue[\s\S]*rememberAwisMaintenance\(\{[\s\S]*action: 'replay_artifacts'[\s\S]*status: 'succeeded'/,
    'Artifact replay can be recorded automatically only when local replay evidence exists.',
  )
  assert.match(
    surface,
    /if \(item\.action === 'update_space_pack'\) \{[\s\S]*const spaces = liveWorkspaceSpaceProjection \?\? workspaceSpaceProjection[\s\S]*if \(!spaces\) continue[\s\S]*saveAwisWorkspaceSpaceProjection\(workspaceKey, spaces\)[\s\S]*action: 'update_space_pack'[\s\S]*status: 'succeeded'/,
    'Space pack refresh can be automatic only when a bounded local Space projection exists.',
  )
  assert.doesNotMatch(
    surface,
    /const AWIS_SAFE_AUTOMATIC_MAINTENANCE_ACTIONS = new Set<AwisWorkspaceMaintenanceAction>\(\[[^\]]*('refresh_folder_map'|'revalidate_command'|'cross_workspace_transfer'|'transfer_learning')[^\]]*\]\)/,
    'Automatic maintenance must not scan folders, revalidate commands or transfer learning without explicit human action.',
  )
})

test('AWIS intelligence treats the folder map as a real command-center gate', () => {
  assert.match(intelligence, /workspaceBrainRequested/)
  assert.match(intelligence, /mapear pasta local/)
  assert.match(intelligence, /recuperar mapa local/)
  assert.match(intelligence, /mapa local/)
  assert.match(intelligence, /comandos inferidos/)
})

test('AWIS workspace memory persists incremental learning without raw source text', () => {
  assert.match(memory, /atlas\.awis\.workspace_memory\.v1/)
  assert.match(memory, /stableSignals/)
  assert.match(memory, /operationalSignals/)
  assert.match(memory, /contextPackAppliedCount/)
  assert.match(memory, /atlas\.awis\.workspace_learning_projection\.v1/)
  assert.match(memory, /buildAwisWorkspaceLearningProjection/)
  assert.match(memory, /atlas\.awis\.workspace_space_projection\.v1/)
  assert.match(memory, /atlas\.awis\.workspace_artifact\.v1/)
  assert.match(memory, /atlas\.awis\.workspace_artifact_lake_summary\.v1/)
  assert.match(memory, /atlas\.awis\.workspace_topology_projection\.v1/)
  assert.match(memory, /buildAwisWorkspaceTopologyProjection/)
  assert.match(memory, /area_refs/)
  assert.match(memory, /component\.areas/)
  assert.match(memory, /Expo\/React Native/)
  assert.match(memory, /topology_ready/)
  assert.match(memory, /atlas\.awis\.workspace_component_memory_projection\.v1/)
  assert.match(memory, /buildAwisWorkspaceComponentMemoryProjection/)
  assert.match(memory, /component_memory: AwisWorkspaceComponentMemoryProjection \| null/)
  assert.match(memory, /atlas\.awis\.workspace_semantic_index_projection\.v1/)
  assert.match(memory, /buildAwisWorkspaceSemanticIndexProjection/)
  assert.match(memory, /semantic_index: AwisWorkspaceSemanticIndexProjection \| null/)
  assert.match(memory, /semantic_index_projection/)
  assert.match(memory, /semantic_matches/)
  assert.match(memory, /atlas\.awis\.workspace_impact_map_projection\.v1/)
  assert.match(memory, /buildAwisWorkspaceImpactMapProjection/)
  assert.match(memory, /impact_map: AwisWorkspaceImpactMapProjection \| null/)
  assert.match(memory, /impact_map_projection/)
  assert.match(memory, /impact_radius/)
  assert.match(memory, /atlas\.awis\.workspace_preflight_projection\.v1/)
  assert.match(memory, /buildAwisWorkspacePreflightProjection/)
  assert.match(memory, /preflight: AwisWorkspacePreflightProjection \| null/)
  assert.match(memory, /preflight_projection/)
  assert.match(memory, /execution_lanes/)
  assert.match(memory, /atlas\.awis\.workspace_twin_projection\.v1/)
  assert.match(memory, /buildAwisWorkspaceTwinProjection/)
  assert.match(memory, /workspace_twin: AwisWorkspaceTwinProjection \| null/)
  assert.match(memory, /workspace_twin_projection/)
  assert.match(memory, /genome_hash/)
  assert.match(memory, /context_autopilot/)
  assert.match(memory, /atlas\.awis\.workspace_relation_projection\.v1/)
  assert.match(memory, /buildAwisWorkspaceRelationProjection/)
  assert.match(memory, /relations_ready/)
  assert.match(memory, /transfer_matrix/)
  assert.match(memory, /shared_context_gold/)
  assert.match(memory, /shared_validation_plans/)
  assert.match(memory, /shared_recovery_patterns/)
  assert.match(memory, /contextGoldLabelsForRelation/)
  assert.match(memory, /validationPlanLabelsForRelation/)
  assert.match(memory, /recoveryPatternLabelsForRelation/)
  assert.match(memory, /shared_evidence_gates/)
  assert.match(memory, /shared_next_session_contracts/)
  assert.match(memory, /evidenceGateLabelsForRelation/)
  assert.match(memory, /nextSessionContractLabelsForRelation/)
  assert.match(memory, /atlas\.awis\.workspace_startup_briefing\.v1/)
  assert.match(memory, /startup_briefing: AwisWorkspaceStartupBriefing \| null/)
  assert.match(memory, /atlas\.awis\.workspace_startup_playbook\.v1/)
  assert.match(memory, /startup_playbook: AwisWorkspaceStartupPlaybook \| null/)
  assert.match(memory, /atlas\.awis\.workspace_task_context_projection\.v1/)
  assert.match(memory, /buildAwisWorkspaceTaskContextProjection/)
  assert.match(memory, /fallbackTaskSignalsFromPack/)
  assert.match(memory, /promptSignals\.length > 0/)
  assert.match(memory, /working_set:/)
  assert.match(memory, /folder_focus:/)
  assert.match(memory, /buildFolderFocusPlan/)
  assert.match(memory, /primary_component: string \| null/)
  assert.match(memory, /task_gold:/)
  assert.match(memory, /buildTaskGoldSelection/)
  assert.match(memory, /evidence_gate:/)
  assert.match(memory, /buildTaskEvidenceGate/)
  assert.match(memory, /context_budget:/)
  assert.match(memory, /task_feedback_loop:/)
  assert.match(memory, /buildTaskFeedbackLoop/)
  assert.match(memory, /update_relations: updateRelations/)
  assert.match(memory, /update_mesh: updateMesh/)
  assert.match(memory, /buildTaskContextBudget/)
  assert.match(memory, /component_intent_ranking/)
  assert.match(memory, /buildComponentIntentRanking/)
  assert.match(memory, /component_context_packs/)
  assert.match(memory, /buildComponentContextPacks/)
  assert.match(memory, /atlas\.awis\.workspace_provider_capsule\.v1/)
  assert.match(memory, /buildAwisWorkspaceProviderCapsule/)
  assert.match(memory, /golden_context:/)
  assert.match(memory, /buildAwisGoldenContextSelection/)
  assert.match(memory, /atlas\.awis\.workspace_bootstrap_manifest_projection\.v1/)
  assert.match(memory, /bootstrap_manifest: AwisWorkspaceBootstrapManifestProjection \| null/)
  assert.match(memory, /buildAwisWorkspaceBootstrapManifestProjection/)
  assert.match(memory, /bootstrap_manifest_projection/)
  assert.match(memory, /learning_contract: \{[\s\S]*capture_outcome: true[\s\S]*update_memory: true/)
  assert.match(memory, /context_reputation:/)
  assert.match(memory, /buildAwisContextReputationOperationalMemory/)
  assert.match(memory, /reputation-gold:/)
  assert.match(memory, /reputation-noisy:/)
  assert.match(memory, /reputação:\$\{item\.label\}:\$\{item\.score\}/)
  assert.match(memory, /ruído:\$\{item\.label\}/)
  assert.match(memory, /promover reputação:\$\{item\.label\}/)
  assert.match(memory, /quarentenar reputação:\$\{item\.label\}/)
  assert.match(memory, /const contextReputation = pack\.memory\?\.operational\.context_reputation \?\? null/)
  assert.match(memory, /task\?\.recommended_context\.load_order|recommended_context: \{[\s\S]*load_order: loadOrder/)
  assert.match(memory, /validationCommands = unique\(\[[\s\S]*contextReputation\?\.revalidate\.map\(\(item\) => `reputação:\$\{item\.label\}`\)/)
  assert.match(contract, /golden_context/)
  assert.match(contract, /const bootstrapManifest = compactObjectRecord\(contextPack\?\.bootstrap_manifest\)/)
  assert.match(contract, /bootstrap_manifest: \{[\s\S]*golden_boot_sequence: compactProviderSafeList\(bootstrapManifest\?\.golden_boot_sequence/)
  assert.match(contract, /bootstrap_manifest: \{[\s\S]*before_send: compactProviderSafeList\(bootstrapManifestAutomation\?\.before_send/)
  assert.match(contract, /bootstrap_manifest: \{[\s\S]*capture_outcome: bootstrapManifestLearning\?\.capture_outcome === true/)
  assert.match(useAtlasAi, /awis_golden_context/)
  assert.match(useAtlasAi, /const bootstrapManifest = objectRecord\(contextPack\?\.bootstrap_manifest\)/)
  assert.match(useAtlasAi, /awis_bootstrap_manifest: \{[\s\S]*golden_boot_sequence: providerSafeStringList\(bootstrapManifest\?\.golden_boot_sequence/)
  assert.match(useAtlasAi, /awis_bootstrap_manifest: \{[\s\S]*capture_outcome: bootstrapManifestLearning\?\.capture_outcome === true/)
  assert.match(useAtlasAi, /AWIS manifesto carregar: \$\{bootstrapManifestLoad\.join\(' \| '\)\}/)
  assert.match(useAtlasAi, /AWIS manifesto provado por: \$\{bootstrapManifestProof\.join\(' \| '\)\}/)
  assert.match(memory, /atlas\.awis\.workspace_execution_doctrine_projection\.v1/)
  assert.match(memory, /buildAwisWorkspaceExecutionDoctrineProjection/)
  assert.match(memory, /execution_doctrine: AwisWorkspaceExecutionDoctrineProjection \| null/)
  assert.match(memory, /doctrine_drivers/)
  assert.match(memory, /preflight_gates/)
  assert.match(memory, /attach_component_keys: true/)
  assert.match(memory, /atlas\.awis\.workspace_provider_strategy_projection\.v1/)
  assert.match(memory, /buildAwisWorkspaceProviderStrategyProjection/)
  assert.match(memory, /provider_strategy: AwisWorkspaceProviderStrategyProjection \| null/)
  assert.match(memory, /task_preferences/)
  assert.match(memory, /providerTaskConfidence/)
  assert.match(memory, /taskProviderStrategy/)
  assert.match(memory, /record_latency: true/)
  assert.match(memory, /provider_hints/)
  assert.match(memory, /provider:prefer:\$\{provider\}/)
  assert.match(memory, /providerStrategyForNextSession/)
  assert.match(memory, /atlas\.awis\.workspace_task_router_projection\.v1/)
  assert.match(memory, /buildAwisWorkspaceTaskRouterProjection/)
  assert.match(memory, /task_router: AwisWorkspaceTaskRouterProjection \| null/)
  assert.match(memory, /record_selected_route: true/)
  assert.match(memory, /intent_signals/)
  assert.match(memory, /evidence_plan/)
  assert.match(memory, /automation_hooks/)
  assert.match(memory, /intentSignalsForTaskRoute/)
  assert.match(memory, /buildTaskRouteEvidencePlan/)
  assert.match(memory, /buildTaskRouteAutomationHooks/)
  assert.match(memory, /routeKey: string \| null/)
  assert.match(memory, /routeLabel: string \| null/)
  assert.match(memory, /contextGoldLabels: string\[\]/)
  assert.match(memory, /buildContextGoldOperationalMemory/)
  assert.match(surface, /contextGoldLabels: taskContext\?\.recommended_context\.task_gold\.map/)
  assert.match(surface, /routeKey: taskContext\?\.task_kind \? `task:\$\{taskContext\.task_kind\}` : null/)
  assert.match(memory, /atlas\.awis\.workspace_continuity_projection\.v1/)
  assert.match(memory, /buildAwisWorkspaceContinuityProjection/)
  assert.match(memory, /continuity: AwisWorkspaceContinuityProjection \| null/)
  assert.match(memory, /atlas\.awis\.workspace_automation_projection\.v1/)
  assert.match(memory, /buildAwisWorkspaceAutomationProjection/)
  assert.match(memory, /external_side_effects_allowed: false/)
  assert.match(memory, /atlas\.awis\.workspace_confidence_projection\.v1/)
  assert.match(memory, /buildAwisWorkspaceConfidenceProjection/)
  assert.match(memory, /confidence: AwisWorkspaceConfidenceProjection \| null/)
  assert.match(memory, /atlas\.awis\.workspace_living_graph_projection\.v1/)
  assert.match(memory, /buildAwisWorkspaceLivingGraphProjection/)
  assert.match(memory, /living_graph: AwisWorkspaceLivingGraphProjection \| null/)
  assert.match(memory, /atlas\.awis\.workspace_context_kernel_projection\.v1/)
  assert.match(memory, /buildAwisWorkspaceContextKernelProjection/)
  assert.match(memory, /context_kernel: AwisWorkspaceContextKernelProjection \| null/)
  assert.match(memory, /atlas\.awis\.workspace_self_improvement_projection\.v1/)
  assert.match(memory, /buildAwisWorkspaceSelfImprovementProjection/)
  assert.match(memory, /self_improvement: AwisWorkspaceSelfImprovementProjection \| null/)
  assert.match(memory, /atlas\.awis\.workspace_memory_freshness_projection\.v1/)
  assert.match(memory, /buildAwisWorkspaceMemoryFreshnessProjection/)
  assert.match(memory, /memory_freshness: AwisWorkspaceMemoryFreshnessProjection \| null/)
  assert.match(memory, /atlas\.awis\.workspace_retention_projection\.v1/)
  assert.match(memory, /buildAwisWorkspaceRetentionProjection/)
  assert.match(memory, /retention: AwisWorkspaceRetentionProjection \| null/)
  assert.match(memory, /atlas\.awis\.workspace_memory_consolidation_projection\.v1/)
  assert.match(memory, /buildAwisWorkspaceMemoryConsolidationProjection/)
  assert.match(memory, /memory_consolidation: AwisWorkspaceMemoryConsolidationProjection \| null/)
  assert.match(memory, /memory_consolidation_projection/)
  assert.match(memory, /normalizeMemoryConsolidationProjection/)
  assert.match(memory, /replay_contract:/)
  assert.match(memory, /replay_contract\.load_first/)
  assert.match(contract, /replay_contract:/)
  assert.match(contract, /compactProviderSafeList\(replayContract\?\.load_first/)
  assert.match(memory, /atlas\.awis\.workspace_startup_orchestration_projection\.v1/)
  assert.match(memory, /buildAwisWorkspaceStartupOrchestrationProjection/)
  assert.match(memory, /startup_orchestration: AwisWorkspaceStartupOrchestrationProjection \| null/)
  assert.match(memory, /atlas\.awis\.workspace_launch_contract_projection\.v1/)
  assert.match(memory, /buildAwisWorkspaceLaunchContractProjection/)
  assert.match(memory, /launch_contract: AwisWorkspaceLaunchContractProjection \| null/)
  assert.match(memory, /launch_contract_projection/)
  assert.match(memory, /atlas\.awis\.current_truth_pack_projection\.v1/)
  assert.match(memory, /current_truth_pack: AwisWorkspaceCurrentTruthPackProjection \| null/)
  assert.match(memory, /current_truth_pack_projection/)
  assert.match(memory, /trust_contract/)
  assert.match(memory, /const contextReputation = input\.memory \? buildAwisContextReputationOperationalMemory\(input\.memory\) : null/)
  assert.match(memory, /contextReputation,\s*spaces: input\.spaces/)
  assert.match(memory, /contextReputation: input\.contextReputation/)
  assert.match(memory, /workspace_notes: string\[\]/)
  assert.match(memory, /workspace_notes: workspaceNotes/)
  assert.match(memory, /knowledge_map\.workspace_notes\.map\(\(item\) => `nota:\$\{item\}`\)/)
  assert.match(memory, /document_hints/)
  assert.match(memory, /truth_hints/)
  assert.match(memory, /doc-regra:\$\{rule\}/)
  assert.match(memory, /doc-sinal:\$\{signal\}/)
  assert.match(memory, /truth-trust:\$\{item\}/)
  assert.match(memory, /truth-check:\$\{item\}/)
  assert.match(memory, /\.\.\.\(input\.topology\?\.knowledge_map\.doc_summaries \?\? \[\]\)/)
  assert.match(memory, /artifactReplay\?\.cold_start_seed\.document_hints/)
  assert.match(memory, /artifactReplay\?\.cold_start_seed\.truth_hints/)
  assert.match(memory, /enhanceAwisWorkspaceNextSessionBrainWithTruth/)
  assert.match(memory, /const documentHints = \{[\s\S]*nextSessionBrainProjections[\s\S]*topologyProjections/)
  assert.match(memory, /const truthHints = \{[\s\S]*truthPackProjections[\s\S]*trust_contract/)
  assert.match(memory, /doc_rules/)
  assert.match(memory, /trust_first/)
  assert.match(memory, /verify_before_send/)
  assert.match(memory, /never_load_raw/)
  assert.match(contract, /component_memory: \{[\s\S]*strongest: strongestComponents/)
  assert.match(contract, /semantic_index: \{[\s\S]*aliases: semanticAliases/)
  assert.match(contract, /task_router: \{[\s\S]*routes: taskRoutes/)
  assert.match(contract, /impact_map: \{[\s\S]*component_impacts: impactComponents/)
  assert.match(contract, /living_graph: \{[\s\S]*golden_path: compactProviderSafeList\(livingGraph\?\.golden_path/)
  assert.match(contract, /workspace_mesh: \{[\s\S]*mesh_hash: compactProviderSafeString\(workspaceMesh\?\.mesh_hash/)
  assert.match(contract, /current_truth_pack: \{[\s\S]*truth_hash: compactProviderSafeString\(currentTruthPack\?\.truth_hash/)
  assert.match(contract, /automation: \{[\s\S]*maintenance_queue: automationQueue/)
  assert.match(contract, /self_improvement: \{[\s\S]*improvement_queue: selfImprovementQueue/)
  assert.match(contract, /const workspaceRunbook = compactObjectRecord\(contextPack\?\.workspace_runbook\)/)
  assert.match(contract, /workspace_runbook: \{[\s\S]*runbook_hash: compactProviderSafeString\(workspaceRunbook\?\.runbook_hash/)
  assert.match(contract, /adaptive_learning: \{[\s\S]*never_automate: compactProviderSafeList\(adaptiveHumanControl\?\.never_automate/)
  assert.match(contract, /provider_strategy: \{[\s\S]*fallback_order: compactProviderSafeList\(providerStrategy\?\.fallback_order/)
  assert.match(contract, /execution_doctrine: \{[\s\S]*required_before_execution: compactProviderSafeList\(doctrinePreflight\?\.required_before_execution/)
  assert.match(contract, /memory_freshness: \{[\s\S]*required_before_promotion: compactProviderSafeList\(freshnessPromotionGate\?\.required_before_promotion/)
  assert.match(contract, /confidence: \{[\s\S]*avoid_until_revalidated: compactProviderSafeList\(confidencePolicy\?\.avoid_until_revalidated/)
  assert.match(contract, /learning_flywheel: \{[\s\S]*next_safe_automations: compactProviderSafeList\(flywheelAutomation\?\.next_safe_automations/)
  assert.match(contract, /launch_contract: \{[\s\S]*first_load: compactProviderSafeList\(launchStartup\?\.first_load/)
  assert.match(contract, /topology: \{[\s\S]*test_commands: compactProviderSafeList\(topologyExecutionMap\?\.test_commands/)
  assert.match(contract, /repository_constellation: \{[\s\S]*constellation_hash: compactProviderSafeString\(repositoryConstellation\?\.constellation_hash/)
  assert.match(memory, /truth-trust:/)
  assert.match(memory, /truth-doc:/)
  assert.match(memory, /truth-check:/)
  assert.match(memory, /atlas\.awis\.workspace_session_gold_projection\.v1/)
  assert.match(memory, /buildAwisWorkspaceSessionGoldProjection/)
  assert.match(memory, /session_gold: AwisWorkspaceSessionGoldProjection \| null/)
  assert.match(memory, /raw_user_message_included: false/)
  assert.match(memory, /taskKind\?: AwisWorkspaceTaskContextProjection\['task_kind'\]/)
  assert.match(memory, /task_memory:/)
  assert.match(memory, /trusted_task_commands/)
  assert.match(memory, /validation_plans/)
  assert.match(memory, /buildTaskValidationPlans/)
  assert.match(memory, /next_session_contract/)
  assert.match(memory, /buildTaskNextSessionContract/)
  assert.match(memory, /recovery_playbook/)
  assert.match(memory, /buildTaskRecoveryPlaybook/)
  assert.match(memory, /evidenceGateLabels/)
  assert.match(memory, /nextSessionLabels/)
  assert.match(memory, /recoveryLabels/)
  assert.match(memory, /adaptiveLearningLabels/)
  assert.match(memory, /adaptive-learning:/)
  assert.match(memory, /learnedNextSessionLoad/)
  assert.match(memory, /learnedEvidenceTrusted/)
  assert.match(memory, /failedRecoveryLabels/)
  assert.match(memory, /tarefa:\$\{input\.taskKind\}/)
  assert.match(memory, /never_start_cold: true/)
  assert.match(memory, /internal_ids_included: false/)
  assert.match(memory, /driftEvents/)
  assert.match(memory, /workspaceBrainFingerprint/)
  assert.doesNotMatch(memory, /readFileSync|read_to_string/)
})
